### ISSUE TITLE
How to require in Sinatra?

### ISSUE THREAD

**Issue by jonathan-alban** [jaredholdcroft/strava-api-v3#1]
Hi, thanks for working on this gem.

Any idea how I can require this gem in Sinatra?

Using Bundlr but getting a 'LoadError' when I try to bundle exec the app.

Thanks.

**Comment by jaredholdcroft** [comment]
Hey,

Are you still having this issue? I can't recreate it using 1.9.3 or 2.1.3 so can you post you app.rb and Gemfile?

**Comment by jaredholdcroft** [comment]
Going to close this for now as I can't recreate any issues. Please re-open if you still have any problems.

**Comment by jonathan-alban** [comment]
Hi @jaredholdcroft sorry I didn't get a chance to reply to you. I don't think this is an issue any more I've been using this Gem in Rails and its been working great and don't think I was loading it right back when I was trying to use it with Sinatra.
