### ISSUE TITLE
uninitialized constant

### ISSUE THREAD

**Issue by konfortes** [jaredholdcroft/strava-api-v3#23]
[19] pry(#<AuthController>)> Strava::Api::V3::Auth
NameError: uninitialized constant Strava::Api::V3::Auth

**Comment by sfandrew** [comment]
@konfortes Did you require the gem?

**Comment by konfortes** [comment]
I did.
Strava::Api::V3 was defined but Strava::Api::V3::Auth wasn't
Anyway, I can't reproduce it anymore. probably something with my code.
thanks!

**Comment by Nino55N** [comment]
also having this issue, Strava::Api::V3 was defined but Strava::Api::V3::Auth wasn't

**Comment by ikottman** [comment]
This is because Auth wasn't added until 0.6.1, and the most recent released version is 0.6.0.

**Comment by jaredholdcroft** [comment]
0.6.1 has been pushed to rubygems.org
