### ISSUE TITLE
Map object polyline

### ISSUE THREAD

**Issue by tke578** [jaredholdcroft/strava-api-v3#24]
My map object polyline does not plot correctly. There seems to be many backslashes added to the response. Anybody else getting this issue?

**Comment by sfandrew** [comment]
You should be using the summary polyline.

**Comment by dblock** [comment]
Works correctly in https://github.com/dblock/run.dblock.org, see https://github.com/dblock/run.dblock.org/blob/gh-pages/Rakefile, sending it directly to Google Maps.
