### ISSUE TITLE
Does authentication still work?

### ISSUE THREAD

**Issue by et** [jaredholdcroft/strava-api-v3#33]
I can do:

```bash
curl -G https://www.strava.com/api/v3/athlete \
    -d access_token=REDACTED
```

and get a response back just fine.

However, when I use this library:
```ruby
> @client = Strava::Api::V3::Client.new(:access_token => REDACTED)
> @client.list_athlete_friends
Strava::Api::V3::ClientError: {"message":"Authorization Error","errors":[]} [HTTP 401]
```

**Comment by yizeng** [comment]
Yes, I believe authentication is working. I have this running in my production envionment, all seem fine.

However, I noticed that `@client.list_athlete_friends` is
> https://www.strava.com/api/v3/athlete/friends

not

> https://www.strava.com/api/v3/athlete

If you try

    curl -G https://www.strava.com/api/v3/athlete/friends \
        -d access_token=REDACTED

does it work?

Maybe Strava have removed listing athlete friends from their API. It's no longer [here](https://strava.github.io/api/v3/athlete/).

**Comment by et** [comment]
Thanks for the response @yizeng. I've been playing around with the API and it seems like the whole thing is botched after the military f-up. Seems like they removed a TON of functionality (including listing friends). Unfortunately, none of the removals were documented hence it seems like a whack-a-mole experience to see what was removed.

**Comment by yizeng** [comment]
@et Yes, seems there have been a lot going on in January 2018 updates and nothing is reflected in [changelog](https://strava.github.io/api/v3/changelog/).

https://groups.google.com/forum/#!topic/strava-api/yk0RsfPEXiw
https://developers.strava.com/docs/january-2018-update/

**Comment by ylecuyer** [comment]
I had the same issue some days ago. Seems that the gem is not compatible with ruby 2.5, I had it to work again when I switched back to ruby 2.3.1 (maybe a more recent version of ruby works)
