### ISSUE TITLE
Strava Oauth flow Update

### ISSUE THREAD

**Issue by mstar0125** [jaredholdcroft/strava-api-v3#38]
I got this message from Strava.
How can we remove grant_type from header for this update?

> Update your Strava OAuth flow by October 15, 2018
> Requests to POST /token with grant_type header will receive a short-lived access token and refresh token starting October 15, 2018.
> On October 15, 2018 the Strava API team will release a refresh token OAuth 2.0 implementation. This date marks the beginning of a migration period during which any requests with a grant_type header will be routed to new authorization logic for refresh tokens, while requests without a grant_type will use the older, existing logic. Both paths will be open for the duration of the migration period, after which the old logic will be deprecated and removed. Rest assured, we will keep both systems working in parallel for a lengthy period. Look out for another email with comprehensive details about refresh tokens and the migration period on October 15, 2018.

**Comment by dblock** [comment]
It doesn't look like the library sends `grant_type` right now, see https://github.com/jaredholdcroft/strava-api-v3/blob/5e96131edfc5ada3374df1287a94e2f4b793026d/lib/strava/api/v3/auth.rb#L14. It also doesn't handle errors here, which is another problem (will try to get to PRing a fix).

I've done the token migration for an app in https://github.com/dblock/slack-strava/pull/50, might be helpful to those trying to do the same.

**Comment by dblock** [comment]
Also https://code.dblock.org/2018/11/17/dealing-with-strava-api-token-migration.html

**Comment by dblock** [comment]
I'm going to move forward with https://github.com/dblock/strava-ruby-client, built from scratch with OAuth refresh token support and more.
