### ISSUE TITLE
Deprecate in favor of strava-ruby-client?

### ISSUE THREAD

**Issue by dblock** [jaredholdcroft/strava-api-v3#41]
There's quite a bit of work necessary to catch up this library to the new OAuth refresh token workflow and other API changes. I've started on that path in https://github.com/jaredholdcroft/strava-api-v3/pull/39 but it got no attention.

I ended up rolling a brand new client in https://github.com/dblock/strava-ruby-client which now covers the whole API as documented and I am happy to maintain that moving forward for my active projects. If @jaredholdcroft wants to stop working on strava-api-v3 here please feel free to just recommend that in README.

**Comment by jaredholdcroft** [comment]
Done
